### ISSUE TITLE
System Natural Scrolling Not Observed in App

### ISSUE THREAD

**Issue by christensen143** [k0kubun/Nocturn#28]
I have natural scrolling setup but the app only allows me to reverse scroll. I'm using the app on Manjaro Linux. Keep up the great work!

**Comment by k0kubun** [comment]
Exactly. But the issue originates from Chrome 39. Can't you reverse scroll on latest Chrome too? See CHANGELOG https://github.com/k0kubun/Nocturn/blob/master/CHANGELOG.md and use old one (inevitable bug is that. But it is decided to be "wontfix"). I gave up to use natural scrolling since I use Chrome too.

**Comment by k0kubun** [comment]
Closing for now. This itself is "wontfix" of Google Chrome, not in Nocturn.
