### ISSUE TITLE
[Mockup] Header design

### ISSUE THREAD

**Issue by CandyFace** [k0kubun/Nocturn#56]
I've been thinking about re-designing the header for Nocturn as I find it a bit lacking currently. The design i've come up with takes full usage of the vertical space in the top and makes the message area fill the entire width of the window. 

The idea is to put important or often used buttons in the middle and less important buttons to the right. 
![image](https://i.imgbox.com/KPp6Wsbe.png)

Whether the design works for Windows or linux though, I don't know.

Also since we don't have a preference panel, or any of the other features implemented yet, the design may vary temporarily.

What's your thought on this @k0kubun

**Comment by k0kubun** [comment]
> takes full usage of the vertical space in the top and makes the message area fill the entire width of the window.

It's a good idea.

> The idea is to put important or often used buttons in the middle and less important buttons to the right.

In your screenshot, I think two changes are applied simultaneously.

1. Move the positions of account selector and characters counter.
2. Add reload, screenshhot and configuration buttons

I think it's a bad UX to have many buttons. I want to keep the design simple. So I'm against 2's changes.

I'm okay to apply 1 change, but how does account selector become?

**Comment by CandyFace** [comment]
The pull-down menu for the account selector would open to the left instead of right, so that shouldn't be too problematic, as far as I know, it's even being done automatically by the browser. The character counter will be hidden by default like is it currently but show when you interact with the message area.

As for the buttons, I agree that too many can create unnecessary clutter and potentially make the UI more difficult to read but I also feel that hiding essential features away in for example the top bar would be bad UX too by adding an unnecessary click. 
I'll revise the design with your comments in mind and update this post when done. The preference and refresh button will be removed but I find the the media upload button too important to hide it away.

**Comment by CandyFace** [comment]
Second iteration: The Media icon has been moved into the message box, right above the text counter. This makes it easy to select and doesn't break the flow of the otherwise clean UI. The message box itself has a gotten a border color again. The active text area will get padding to the right that will make it impossible to overflow the icon and counter.

The account selector has been moved a bit and now includes a small arrow down shape to emphasis that it's an icon and a pull-down menu will appear when clicked.

To keep the look even more simplistic, we could possibly hide the media icon when the text area is not focused, like the counter.
  
![design 2](https://cloud.githubusercontent.com/assets/1045397/20524542/3d975720-b0bb-11e6-90f8-760ed504f918.png)

Here you can see an example of what it could look like when the account selector button is pressed.
![design 2 - pulldown](https://cloud.githubusercontent.com/assets/1045397/20524551/433a59fc-b0bb-11e6-87fc-0a478dd1f580.png)

**Comment by k0kubun** [comment]
Looks good. Maybe camera mark will be omitted at first since we don't have such a feature for now.

The next question is:
Can we achieve the first purpose, "makes the message area fill the entire width of the window", with this layout?

I think this design requires right padding in the message area to avoid text overlaps with a camera button and a character counter. And I guess current width of account selector is small enough to utilize window's width.

So we may achieve the same purpose by changing current design to a following Nocturn v0 layout:

![](https://camo.githubusercontent.com/3a74ac841019ce461ba1ce8188605ae16f58aeae/68747470733a2f2f692e6779617a6f2e636f6d2f62653931653739383638366330613833613839623962343261393462323463312e676966)

And I prefer it because I put frequently used buttons to a righter place and I have to move my pointer wide to click account selector in your design.

I think design changes must have some benefits that an old design doesn't have. Why is your proposal more convenient than a current layout?

**Comment by CandyFace** [comment]
> Can we achieve the first purpose, "makes the message area fill the entire width of the window", with this layout?

This has been achieved already, the message box itself takes the entire width of the window, which is what I wanted. The active text field inside is something else though, and requires padding to the right like I said in my last post. 


> So we may achieve the same purpose by changing current design to a following Nocturn v0 layout:

Well yes sorta but then you would be iterating backwards, which is usually something you wouldn't do in an design cycle. Beside that your new design feels more fresh and uplifting, instead of dull and grey. The old design also carries a few things that I find unnecessary, some of these are:
- The title on unix and macOS, only windows use it and therefore I think it's wasteful to have it, which is why I like your new design a bit more than the old. 
- The home button useless when all the menu's are literally next to each other. 
 
you said you wanted a simple design, something I think my proposal portrays better than your old. 


> I think design changes must have some benefits that an old design doesn't have. Why is your proposal more convenient than a current layout?

The proposal doesn't have any usability benefits over the current or the old design at present, it does however make a bit better use of the space, which when I compare to the current design, makes it feel more future proof for new feature. 

> And I prefer it because I put frequently used buttons to a righter place and I have to move my pointer wide to click account selector in your design. So I'm okay to rollback a current design to v0-like one.

My preferred location of buttons are to the right, away from my eyes and interaction. When I look at the old design above, The placement of the account selector is jarring to my eye and I get the assumption that something is attached to the message. Beside that I don't find the account selector important enough to want it in my text field. Do you really use it so often that you need it all the time?

We could move the account selector next to the traffic lights, but that would make the left side of the header more dominant than the right and create visual unbalance.

**Comment by k0kubun** [comment]
> instead of dull and grey. The old design also carries a few things that I find unnecessary, some of these are:
>
> The title on unix and macOS, only windows use it and therefore I think it's wasteful to have it, which is why I like your new design more than the old.
> The home button is useless when all the menu's are literally next to each other.

Ah sorry my statements were poor. My intention was only about a textarea. Just talking about removing a border (padding?) around a textarea, not using grey color or adding buttons.

> makes it feel more future proof for new feature.

I couldn't understand what you mean by "more future proof". Please describe more details.

> Beside that I don't find the account selector important enough to want it in my text field. Do you really use it so often that you need it so close to the text you're typing?

Good point. Personally I don't click account selector and use shortcut keys instead. But I check what account I use to post a tweet everytime I do it. So I want it to be in an easy-to-see place. When I'm writing a tweet, I'm seeing the text and it's reasonable to add it to a so close place.

> We could move the account selector next to the traffic lights, but that would make the left side of the header more dominant than the right and create visual unbalance.

I think so too. So I decided to put it in the current place.

<hr>

And extra important point for your next proposal. The layout can't be achieved on Linux or Windows since we can't remove a title bar from window on these platforms. I intentionally avoid adding buttons to that place. WDYT?

**Comment by CandyFace** [comment]
> Ah sorry my statements were poor. My intention was only about a textarea. Just talking about removing a border (padding?) around a textarea, not using grey color or adding buttons.

Sure that would be fine too.

To clarify, when I say padding I mean white space inside an element. The border is the light blue'ish color outline which is on the current design and my last proposal. You want that removed?

> I couldn't understand what you mean by "more future proof". Please describe more details.

Future proof, as in possible to expand with more elements, eg. an upload/media button. I find it difficult to expand the current design with elements without altering the size of the header or width of the overall window.

> And extra important point for your second proposal. The layout can't be achieved on Linux or Windows since we can't remove a title bar from window on these platforms. I intentionally avoid adding buttons to that place. WDYT?

Damn I feared that, that might have been the case... hmm.

**Comment by CandyFace** [comment]
Third iteration: 
I still wanted to emphasis that the account changer icon is actually a button, to make a bit more visually readable, also the icon has been enlarged a bit too The message box is a tad bigger and the text and media icon still reside inside the that field too. Like before the active textfield would still require a bit of padding for not overlapping.

So in the end I ended up with something much similar to the current, just tweaked a bit.. whether you want to apply those changes though is up to you.
![iteration3](https://cloud.githubusercontent.com/assets/1045397/20568309/5e237e56-b19c-11e6-8227-fb9774380f24.png)

**Comment by k0kubun** [comment]
> Future proof, as in possible to expand with more elements, eg. an upload/media button.

OK, you want to add an upload/media button. I got it.

In that point of view, the important part of your proposal is having a right padding inside textarea to put an upload/media button. Other tweaks (an arrow beside icon and a position of character counter) are optional for your problem. However, if you think it's necessary to balance a layout with upload/media button, it's acceptable to move character counter's position.

<hr>

Before you implement it, I have some recommendations to accept your changes easily.

- Next changes for account selector should work with latest Electron. Otherwise it'll be modified again in the future. Actually a current implementation using select tag doesn't work with it.
- Keep writable region of textarea as wide as possible. My window's width is usually small [like this](https://cloud.githubusercontent.com/assets/3138447/20572056/2d1c0372-b1ed-11e6-8e46-4a64cfdbe4cd.png).
- If you implement media button, consider using https://gyazo.com/api/docs/image#upload and a url field in the response. We can upload an image without compression and I confirmed from the service's team that it's acceptable to use the url directly in Nocturn in terms of service.
  - Of course Twitter's official API is acceptable too. Though it'll be compressed.
