### ISSUE TITLE
RTL Languages text alignment

### ISSUE THREAD

**Issue by K0njkav** [k0kubun/Nocturn#60]
Hi
RTL Languages (like:arabic, persian...) are supported on twitter website and tweets shows in the correct alignment  right-to-left). In app RTL tweets are in the same text alignment as English (LTR). Can you fix this please?

**Comment by k0kubun** [comment]
This is a fair request, but it's been 3 years since your proposal. So I'd like to check if you're still interested in this. Please reopen this if you (or any other person) need one.

Also, I'd appreciate an example tweet or user with RTL languages for testing the feature when this is reopened. Thanks.
